import { Barlow_Condensed, Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/shared/Navbar";
import CountryModal from "@/components/modal/CountryModal";
import { TanstackProvider } from "@/context/TanstackProvider";
import "./globals.css";
import TopBar from "@/components/shared/Topbar";
import Footer from "@/components/shared/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const barlow = Barlow_Condensed({
  variable: "--font-barlow-condensed",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Bitss Security Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={barlow.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanstackProvider>
          <CountryModal />
          <TopBar />
          <Navbar />
          <main className="bg-white text-slate-900 min-h-screen">
            {children}
          </main>
          <Footer />
        </TanstackProvider>
      </body>
    </html>
  );
}
